packages:
  - "apps/*"
  - "packages/shared/*"
  - "tooling/*"

allowBuilds:
  "@swc/core": true
  esbuild: true
  unrs-resolver: false

patchedDependencies:
  "@native-sdk/cli@0.9.0": "patches/@native-sdk__cli@0.9.0.patch"
